### ISSUE TITLE
Error with predict.py

### ISSUE THREAD

**Issue by Akhmetzhan** [jlcsilva/EfficientUNetPlusPlus#4]
Dear authors,
Great thanks for sharing the code. I wanted to use your model to predict on my own data. I used you proposed code: python predict.py -d Coronary -i <filename>.
However, there is an error - TypeError: _init_() got unexpected keyword argument "channel_multiplier"
Please, could you help me with this issue? Great thanks in advance

**Comment by jlcsilva** [comment]
Hey!
Which version of timm are you using? Downgrading to timm==0.4.12 should work. However, it may require you to downgrade PyTorch as well. 
Another option is to keep the current timm version and change the segmentation_models_pytorch/encoders/timm_efficientnet.py file instead. For that you need only modify the model_kwargs variable in the function get_efficientnet_kwargs to
```
    model_kwargs = dict(
        block_args=decode_arch_def(arch_def, depth_multiplier),
        num_features=round_channels(1280, channel_multiplier, 8, None),
        stem_size=32,
        round_chs_fn=partial(round_channels, multiplier=channel_multiplier),
        act_layer=Swish,
        drop_rate=drop_rate,
        drop_path_rate=0.2,
    )
```
and in the function gen_efficientnet_lite_kwargs to 
```
    model_kwargs = dict(
        block_args=decode_arch_def(arch_def, depth_multiplier, fix_first_last=True),
        num_features=1280,
        stem_size=32,
        fix_stem=True,
        round_chs_fn=partial(round_channels, multiplier=channel_multiplier),
        act_layer=nn.ReLU6,
        drop_rate=drop_rate,
        drop_path_rate=0.2,
    )
```
Hope this works. If it doesn't, let me know!

**Comment by Akhmetzhan** [comment]
![image](https://user-images.githubusercontent.com/63834502/171781556-30ea4785-eb31-474a-806a-504dfd864047.png)
![image](https://user-images.githubusercontent.com/63834502/171781685-610af2bd-1fae-46fd-a76a-90dbdc85d193.png)
Dear João Lourenço Silva,
Great thanks for your help. I followed to all recommendations. I downgraded both timm (0.4.12) and pytorch packages.  However, it provided the same error - TypeError: init() got unexpected keyword argument "channel_multiplier".

Then, I changed the file you mentioned (segmentation_models_pytorch/encoders/timm_efficientnet.py). But, it showed me a new error:
NameError: name "partial" is not defined.
Could you please provide your advice on what I should do in order to use the predict.py for segmentation task?
Great thanks in advance.
Looking forward for your reply.
Kind regards,

**Comment by Akhmetzhan** [comment]
![image](https://user-images.githubusercontent.com/63834502/171792083-31f685ae-23ae-4cb4-91d9-978c8cb8adc3.png)
Dear João Lourenço Silva,
I have added the lines: from functools import partial. And, the previous error has been disappeared. However, there is a  new error: 
FileNotFoundError: [Errno 2] No such file or directory: 'MODEL.pth'

What argument should I place for -m variable? I would be very grateful if you could help with this issue.
Thanks in advance.
Looking forward to your reply.
Kind regards,

**Comment by jlcsilva** [comment]
Hey Akhmetzhan,
The argument should be the path to the .pth file containing the model weights. At this time, I am not allowed to share my model weights nor training data. To obtain a model you'll have to get training data and train a model yourself.
Best regards,
João

**Comment by Akhmetzhan** [comment]
Dear  João Lourenço Silva,
Great thanks for your response. I am a novel user of Python, that is why I am asking you such a basic questions. Could you please provide your advise if there any ready-to-use software (maybe open-source) which a user could use for segmentation of their own images?
Thanks in advance

**Comment by jlcsilva** [comment]
Akhmetzhan,
It depends on the application and the required level of performance. However, it's probably better if we close this issue and you contact me by email: [joao.lourenco.silva@tecnico.ulisboa.pt](mailto:joao.lourenco.silva@tecnico.ulisboa.pt)
